### ISSUE TITLE
set_signal_handler2 exits always

### ISSUE THREAD

**Issue by rednach** [Alignak-monitoring-contrib/alignak-module-ws#111]
exit(12) at https://github.com/Alignak-monitoring-contrib/alignak-module-ws/blob/develop/alignak_module_ws/ws.py#L1837 kills the module, so modulesmanager is trying to restart it forever...

**Comment by mohierf** [comment]
WTF ... sorry for this! I will fix rapidly !

**Comment by mohierf** [comment]
Indeed, I added this function to make some tests about killing modules. This function is not, anyway, useful because it exists in the Alignak BaseModule class which is inherited by the module ... but it looks like if it is never called. The problem you found shows that it is called ! 😞

**Comment by rednach** [comment]
I am an expert in this kind of ... errors. Thank you for your rapid response!

**Comment by mohierf** [comment]
Indeed, I added this function to make some tests for Alignak killing the modules. This function is not, anyway, useful because it exists in the Alignak BaseModule class which is inherited by the module ... but it looks like if it is never called. The problem you found shows that it is called ! 😞

**Comment by mohierf** [comment]
I removed the signals management from the module to use the fucntions of the base class. This modification arose a small problem with the unit tests and I also fixed this. Travis tests in progress...
