### ISSUE TITLE
Alignak not listed as required

### ISSUE THREAD

**Issue by lnlrbr** [Alignak-monitoring-contrib/alignak-module-ws#82]
Missing module alignak as a requirement for install

**Comment by mohierf** [comment]
For sure, alignak is needed for the WS module, but is it a good idea to include it automatically as a requirement? @ddurieux : what do you think about it?

**Comment by ddurieux** [comment]
We had not defined `alignak` in others modules, mainly because had problems in tests (not sure about that, need check it). But I think `alignak` must be in requirements
